### PR TITLE
Fix #331 java 11 illegal access warnings

### LINKED ISSUE #331: illegal reflective access operation with 1.3.2 and openjdk11
I'm testing rd cli with openjdk11 and I'm seeing this issue, starting from 1.3.2. 1.3.1 is fine.
1.3.2 is fine with openjdk8

It is only a warning, but maybe useful to know.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/rundeck/bin/rundeck-cli.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

### PR DESCRIPTION
**Pull request by gschueler**
quell warnings caused by Retrofit 2.8
https://github.com/square/retrofit/issues/3341

### CODE REVIEW

**Comment by halradaideh** [comment]
still appears with rdcli 1.3.4 and rd 3.3.4 and jdk 11

`
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/usr/lib/retrofit-2.9.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
`

**Comment by gschueler** [comment]
@halradaideh What method do you use to install rd-cli ?

**Comment by halradaideh** [comment]
i download the release using wget and move it to a proper path

**Comment by gschueler** [comment]
@halradaideh the executable jar file you mean? ok thanks

**Pull request merged**
